/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.latihan.javagui;

import java.awt.TextField;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rifky
 */
public class namaNilaiRata extends javax.swing.JFrame {
	Ratarata rata = new Ratarata();

	/**
	 * Creates new form namaNilaiRata
	 */
	public namaNilaiRata() {
		initComponents();
		nonAktif();
	}

	void Bersih() {
		Nilai_1.setText("");
		Nilai_2.setText("");
		rata_rata.setText("");
	}

	void Aktif(){
		Nilai_1.setEnabled(true);
		Nilai_2.setEnabled(true);
		rata_rata.setEnabled(true);
	}

	void nonAktif(){
		Nilai_2.setEnabled(false);
		rata_rata.setEnabled(false);
	}

	





	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                Nilai_1 = new javax.swing.JTextField();
                Nilai_2 = new javax.swing.JTextField();
                Hitung = new javax.swing.JButton();
                Bersih = new javax.swing.JButton();
                Tutup = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                rata_rata = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(0, 242, 242));

                jLabel1.setText("Menghitung Rata - Rata");

                jLabel2.setText("Nilai 1");

                jLabel3.setText("Nilai 2");

                Nilai_1.addInputMethodListener(new java.awt.event.InputMethodListener() {
                        public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                        }
                        public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                                Nilai_1InputMethodTextChanged(evt);
                        }
                });
                Nilai_1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Nilai_1ActionPerformed(evt);
                        }
                });
                Nilai_1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                Nilai_1KeyPressed(evt);
                        }
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                Nilai_1KeyTyped(evt);
                        }
                });

                Nilai_2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Nilai_2ActionPerformed(evt);
                        }
                });
                Nilai_2.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                Nilai_2KeyTyped(evt);
                        }
                });

                Hitung.setText("Hitung");
                Hitung.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HitungActionPerformed(evt);
                        }
                });

                Bersih.setText("Bersih");
                Bersih.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BersihActionPerformed(evt);
                        }
                });

                Tutup.setText("Tutup");
                Tutup.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TutupActionPerformed(evt);
                        }
                });

                jLabel4.setText("Rata-rata");

                rata_rata.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rata_rataActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Nilai_2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Nilai_1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Hitung)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Bersih)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tutup))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rata_rata, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(154, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(Nilai_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(Nilai_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Hitung)
                                        .addComponent(Bersih)
                                        .addComponent(Tutup))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(rata_rata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(123, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void Nilai_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai_1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_Nilai_1ActionPerformed

        private void Nilai_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai_2ActionPerformed
                // TODO add your handling code here:
	
		
			
        }//GEN-LAST:event_Nilai_2ActionPerformed

        private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
                // TODO add your handling code here:
		Bersih();
		Nilai_1.requestFocus();
		nonAktif();
		


        }//GEN-LAST:event_BersihActionPerformed

        private void rata_rataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rata_rataActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_rata_rataActionPerformed

        private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
                // TODO add your handling code here:
		rata.setNilai1(Double.parseDouble(Nilai_1.getText()));
		rata.setNilai2(Double.parseDouble(Nilai_2.getText()));
		rata_rata.setText(Double.toString(rata.getNilaiRata()));
		rata_rata.setEnabled(true);
        }//GEN-LAST:event_HitungActionPerformed

        private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
                // TODO add your handling code here:
		int tutup;
		tutup = JOptionPane.showConfirmDialog(null, "Tutup program?","Konfirmasi",JOptionPane.YES_NO_OPTION);
		if (tutup == JOptionPane.YES_OPTION) {
			dispose();
		}
		else {
		}
	
        }//GEN-LAST:event_TutupActionPerformed

        private void Nilai_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nilai_1KeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			
		
		}
        }//GEN-LAST:event_Nilai_1KeyPressed

        private void Nilai_1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Nilai_1InputMethodTextChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_Nilai_1InputMethodTextChanged

        private void Nilai_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nilai_1KeyTyped
                // TODO add your handling code here:
		char c = evt.getKeyChar();
		if (!Character.isDigit(c)){
			evt.consume(); // Meng-ignore non-numeric character
		}
		else {
			Nilai_2.setEnabled(true);

		}


        }//GEN-LAST:event_Nilai_1KeyTyped

        private void Nilai_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nilai_2KeyTyped
                // TODO add your handling code here:
		char c = evt.getKeyChar();
		if (!Character.isDigit(c)){
			evt.consume(); // Meng-ignore non-numeric character
		}
        }//GEN-LAST:event_Nilai_2KeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(namaNilaiRata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(namaNilaiRata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(namaNilaiRata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(namaNilaiRata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new namaNilaiRata().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Bersih;
        private javax.swing.JButton Hitung;
        private javax.swing.JTextField Nilai_1;
        private javax.swing.JTextField Nilai_2;
        private javax.swing.JButton Tutup;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField rata_rata;
        // End of variables declaration//GEN-END:variables
}
