/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahmakan;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rifky
 */
public class FormOshiNe extends javax.swing.JFrame {
	Menu menuHarga  = new Menu();


	/**
	 * Creates new form FormOshiNe
	 */
	public FormOshiNe() {
		initComponents();
		nonAktif();

		hargaAir.setEnabled(false);
		hargaJuice.setEnabled(false);
		namaPaket.setEnabled(false);
		
	}

	// Paket Makanan
	private void paketMakanan_off(){
		paketMakanan.setSelectedIndex(0);
	}

	private void hargaPaketMakanan_off(){
		hargaPaketMakanan.setText("");
		hargaPaketMakanan.setEnabled(false);
	}
	private void jumlahPaketMakanan_off(){
		jumlahPaketMakanan.setText("");
		jumlahPaketMakanan.setEnabled(false);

	}
	private void jumlahPaketMakanan_on(){
		jumlahPaketMakanan.setEnabled(true);
	}

	// Minuman
	private void air_off(){
		air.setSelected(false);
		jumlahAir.setText("");
		hargaAir.setText("");

	}


	private void juice_off(){
		juice.setSelected(false);
		jumlahJuice.setText("");
		hargaJuice.setText("");

	}

	private void jenisPelayanan_off(){
		jenisPelayanan.setSelectedIndex(0);
	}

	private void tarif_off(){
		tarif.setEnabled(false);
		tarif.setText("");
	}

	private void totalBayar_off(){
		totalBayar.setText("");
	}
	private void hargaTarif_off(){
		hargaTarif.setText("");
	}
	private void tampilanTotal_off(){
		tampilanTotal.setText("");
	}
	private void uangBayar_off(){
		uangBayar.setText("");
	}
	private void uangKembali_off(){
		uangKembali.setText("");
	}




	// nonAktif
	private void nonAktif(){
		paketMakanan_off();
		jenisPelayanan_off();
		hargaPaketMakanan_off();
		jumlahPaketMakanan_off();
		air_off();
		juice_off();
		tarif_off();
		totalBayar_off();
		hargaTarif_off();
		tampilanTotal_off();
		uangBayar_off();
		uangKembali_off();

	}

	private void bersih(){
		nonAktif();
		namaPaket.setText("");

		menuHarga.hargaPaket = 0;
		menuHarga.jumlahPaketMakanan= 0;
		menuHarga.air = 0;
		menuHarga.juice = 0;
		menuHarga.totalBayar = 0;
		menuHarga.hargaTarif = 0;
		menuHarga.uangBayar= 0;
		menuHarga.uangKembali= 0;
		menuHarga.tarif = 0;
		menuHarga.total = 0;

	}



	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                air = new javax.swing.JCheckBox();
                juice = new javax.swing.JCheckBox();
                jumlahJuice = new javax.swing.JTextField();
                jumlahAir = new javax.swing.JTextField();
                jLabel19 = new javax.swing.JLabel();
                hargaJuice = new javax.swing.JTextField();
                hargaAir = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                paketMakanan = new javax.swing.JComboBox<>();
                jLabel11 = new javax.swing.JLabel();
                hargaPaketMakanan = new javax.swing.JTextField();
                jLabel12 = new javax.swing.JLabel();
                jumlahPaketMakanan = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                namaPaket = new javax.swing.JTextField();
                jLabel23 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jenisPelayanan = new javax.swing.JComboBox<>();
                jLabel15 = new javax.swing.JLabel();
                tarif = new javax.swing.JTextField();
                jLabel17 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jLabel20 = new javax.swing.JLabel();
                totalBayar = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();
                hargaTarif = new javax.swing.JTextField();
                jLabel16 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                uangBayar = new javax.swing.JTextField();
                jLabel22 = new javax.swing.JLabel();
                uangKembali = new javax.swing.JTextField();
                jLabel18 = new javax.swing.JLabel();
                tampilanTotal = new javax.swing.JTextField();
                bersih = new javax.swing.JButton();

                jLabel4.setText("jLabel4");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(242, 151, 15));

                jPanel2.setBackground(new java.awt.Color(242, 151, 15));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setText("FOOD COURT");

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("Oishi Ne");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(417, 417, 417)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(26, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MINUMAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("PILIH MINUMAN");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("JUMLAH");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                air.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                air.setText("Air Mineral");
                air.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                airActionPerformed(evt);
                        }
                });

                juice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                juice.setText("Juice");
                juice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                juiceActionPerformed(evt);
                        }
                });
                juice.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                juiceKeyPressed(evt);
                        }
                });

                jumlahJuice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlahJuiceActionPerformed(evt);
                        }
                });
                jumlahJuice.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jumlahJuiceKeyPressed(evt);
                        }
                });

                jumlahAir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlahAirActionPerformed(evt);
                        }
                });
                jumlahAir.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jumlahAirKeyPressed(evt);
                        }
                });

                jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel19.setText("HARGA");

                hargaJuice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hargaJuiceActionPerformed(evt);
                        }
                });
                hargaJuice.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                hargaJuiceKeyPressed(evt);
                        }
                });

                hargaAir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hargaAirActionPerformed(evt);
                        }
                });
                hargaAir.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                hargaAirKeyPressed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(air, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3)
                                        .addComponent(juice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jumlahAir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jumlahJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(hargaJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(hargaAir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel19))
                                                .addGap(30, 112, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(87, 87, 87))))
                );

                jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jumlahAir, jumlahJuice});

                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(air))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel19))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jumlahAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(hargaAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jumlahJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(hargaJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(juice)))
                                .addContainerGap(132, Short.MAX_VALUE))
                );

                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAKET MAKANAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel9.setText("PILIH PAKET MAKANAN");

                paketMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "PAKET 1", "PAKET 2", "PAKET 3" }));
                paketMakanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                paketMakananActionPerformed(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel11.setText("HARGA PAKET");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel12.setText("JUMLAH");

                jumlahPaketMakanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlahPaketMakananActionPerformed(evt);
                        }
                });
                jumlahPaketMakanan.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jumlahPaketMakananKeyPressed(evt);
                        }
                });

                jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                namaPaket.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                namaPaketActionPerformed(evt);
                        }
                });

                jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel23.setText("NAMA PAKET");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                        .addGap(209, 209, 209)
                                                                        .addComponent(jLabel13))
                                                                .addComponent(hargaPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(107, 107, 107))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(paketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jumlahPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addContainerGap()))))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel12)
                                                .addComponent(jumlahPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(paketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(hargaPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(namaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(102, Short.MAX_VALUE))
                );

                jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JENIS PELAYANAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel10.setText("PILIH PELAYANAN");

                jenisPelayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Take Away", "Delivery" }));
                jenisPelayanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jenisPelayananActionPerformed(evt);
                        }
                });

                jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel15.setText("TARIF");

                tarif.setColumns(3);

                jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel10))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jenisPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(107, 107, 107))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jenisPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addContainerGap(142, Short.MAX_VALUE))
                );

                jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL BAYAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                totalBayar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                totalBayarActionPerformed(evt);
                        }
                });

                jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel14.setText("TOTAL HARGA PAKET & MINUMAN");

                hargaTarif.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hargaTarifActionPerformed(evt);
                        }
                });

                jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel16.setText("HARGA TARIF");

                jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel21.setText("UANG BAYAR");

                uangBayar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                uangBayarActionPerformed(evt);
                        }
                });
                uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                uangBayarKeyPressed(evt);
                        }
                });

                jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel22.setText("UANG KEMBALI");

                uangKembali.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                uangKembaliActionPerformed(evt);
                        }
                });

                jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel18.setText("TOTAL");

                tampilanTotal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tampilanTotalActionPerformed(evt);
                        }
                });

                bersih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                bersih.setText("BERSIH");
                bersih.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bersihActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(bersih)
                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel16)
                                                                .addComponent(jLabel18)
                                                                .addComponent(jLabel21)
                                                                .addComponent(jLabel14)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(hargaTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tampilanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(uangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(442, 442, 442)
                                                .addComponent(jLabel20)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel20))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(hargaTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16))
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tampilanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel18))))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(uangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(bersih)
                                .addGap(15, 15, 15))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel6});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5, jPanel6});

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jumlahPaketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPaketMakananActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlahPaketMakananActionPerformed

        private void totalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_totalBayarActionPerformed

        private void paketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketMakananActionPerformed
                // TODO add your handling code here:
		if(paketMakanan.getSelectedItem().toString().equalsIgnoreCase("PILIH")){
			// menjadi 0
			menuHarga.setJumlahPaketMakanan(0);
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

			menuHarga.setHargaPaket(paketMakanan.getSelectedItem().toString());
			namaPaket.setText("");
			hargaPaketMakanan_off();
			jumlahPaketMakanan_off();

		}
		else{
			jumlahPaketMakanan_on();
			menuHarga.setHargaPaket(paketMakanan.getSelectedItem().toString());
			hargaPaketMakanan.setText(String.valueOf(menuHarga.getHargaPaket()));
			namaPaket.setText(menuHarga.namaPaket);
		}
        }//GEN-LAST:event_paketMakananActionPerformed

        private void jumlahPaketMakananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahPaketMakananKeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			if(jumlahPaketMakanan.getText().equalsIgnoreCase("")){
				menuHarga.setJumlahPaketMakanan(0);
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

			}
			else {
				menuHarga.setJumlahPaketMakanan(Integer.parseInt(jumlahPaketMakanan.getText()));
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));
			}
		}
        }//GEN-LAST:event_jumlahPaketMakananKeyPressed

        private void jenisPelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisPelayananActionPerformed
                // TODO add your handling code here:
		if(jenisPelayanan.getSelectedItem().toString().equalsIgnoreCase("PILIH")){


		}
		else{
			menuHarga.setPelayanan(jenisPelayanan.getSelectedItem().toString());
			tarif.setText(menuHarga.getPelayanan());
			menuHarga.setHargaTarif();
			hargaTarif.setText(String.valueOf(menuHarga.getHargaTarif()));

			menuHarga.setTotal();
			tampilanTotal.setText(String.valueOf(menuHarga.getTotal()));
			
		}

        }//GEN-LAST:event_jenisPelayananActionPerformed

        private void hargaTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTarifActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaTarifActionPerformed

        private void uangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangBayarActionPerformed
                // TODO add your handling code here:
		
        }//GEN-LAST:event_uangBayarActionPerformed

        private void uangKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangKembaliActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_uangKembaliActionPerformed

        private void tampilanTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilanTotalActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_tampilanTotalActionPerformed

        private void uangBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyPressed
                // TODO add your handling code here:

		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			menuHarga.setUangBayar(Double.parseDouble(uangBayar.getText()));

			if(menuHarga.getUangBayar() >= menuHarga.getTotal()){
				menuHarga.setUangKembali();
				uangKembali.setText(String.valueOf(menuHarga.getUangKembali()));
			}
			else {
				menuHarga.setUangBayar(0);
				uangBayar.setText("");
				JOptionPane.showMessageDialog(null, "Pembayaran Kurang!", "Warning", JOptionPane.OK_OPTION);
				
			}

		}
        }//GEN-LAST:event_uangBayarKeyPressed

        private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
                // TODO add your handling code here:
		bersih();
        }//GEN-LAST:event_bersihActionPerformed

        private void jumlahJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahJuiceActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlahJuiceActionPerformed

        private void jumlahJuiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahJuiceKeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			menuHarga.setJuice(Integer.parseInt(jumlahJuice.getText()));
			hargaJuice.setText(String.valueOf(menuHarga.getJuice()));
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

		}
        }//GEN-LAST:event_jumlahJuiceKeyPressed

        private void jumlahAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahAirActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlahAirActionPerformed

        private void jumlahAirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahAirKeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			menuHarga.setAir(Integer.parseInt(jumlahAir.getText()));
			hargaAir.setText(String.valueOf(menuHarga.getAir()));
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));


		}
        }//GEN-LAST:event_jumlahAirKeyPressed

        private void airActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airActionPerformed
                // TODO add your handling code here:
		if(air.isSelected()){
			menuHarga.setAir(1);
			jumlahAir.setText("1");
			hargaAir.setText(String.valueOf(menuHarga.getAir()));
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));


		}
		else{
			menuHarga.setAir(0);
			jumlahAir.setText("");
			hargaAir.setText("");
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

		}
        }//GEN-LAST:event_airActionPerformed

        private void hargaJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaJuiceActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaJuiceActionPerformed

        private void hargaJuiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaJuiceKeyPressed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaJuiceKeyPressed

        private void hargaAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaAirActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaAirActionPerformed

        private void hargaAirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaAirKeyPressed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaAirKeyPressed

        private void juiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_juiceKeyPressed
                // TODO add your handling code here:
        }//GEN-LAST:event_juiceKeyPressed

        private void juiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juiceActionPerformed
                // TODO add your handling code here:
		if(juice.isSelected()){
			menuHarga.setJuice(1);
			jumlahJuice.setText("1");
			hargaJuice.setText(String.valueOf(menuHarga.getJuice()));
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));
			

		}
		else{
			menuHarga.setJuice(0);
			jumlahJuice.setText("");
			hargaJuice.setText("");
			menuHarga.setTotalBayar();
			totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

		}
        }//GEN-LAST:event_juiceActionPerformed

        private void namaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPaketActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_namaPaketActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormOshiNe().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox air;
        private javax.swing.JButton bersih;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JTextField hargaAir;
        private javax.swing.JTextField hargaJuice;
        private javax.swing.JTextField hargaPaketMakanan;
        private javax.swing.JTextField hargaTarif;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JComboBox<String> jenisPelayanan;
        private javax.swing.JCheckBox juice;
        private javax.swing.JTextField jumlahAir;
        private javax.swing.JTextField jumlahJuice;
        private javax.swing.JTextField jumlahPaketMakanan;
        private javax.swing.JTextField namaPaket;
        private javax.swing.JComboBox<String> paketMakanan;
        private javax.swing.JTextField tampilanTotal;
        private javax.swing.JTextField tarif;
        private javax.swing.JTextField totalBayar;
        private javax.swing.JTextField uangBayar;
        private javax.swing.JTextField uangKembali;
        // End of variables declaration//GEN-END:variables
}
