/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahmakan;

import java.awt.event.KeyEvent;

/**
 *
 * @author rifky
 */
public class FormOshiNe extends javax.swing.JFrame {
	Menu menuHarga  = new Menu();


	/**
	 * Creates new form FormOshiNe
	 */
	public FormOshiNe() {
		initComponents();
		hargaPaketMakanan_off();
		hargaMinuman_off();
		
	}

	private void hargaPaketMakanan_off(){
		hargaPaketMakanan.setEnabled(false);
	}
	private void hargaMinuman_off(){
		hargaMinuman.setEnabled(false);
	}



	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                minuman = new javax.swing.JComboBox<>();
                jLabel6 = new javax.swing.JLabel();
                hargaMinuman = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jumlahMinuman = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                paketMakanan = new javax.swing.JComboBox<>();
                jLabel11 = new javax.swing.JLabel();
                hargaPaketMakanan = new javax.swing.JTextField();
                jLabel12 = new javax.swing.JLabel();
                jumlahPaketMakanan = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jenisPelayanan = new javax.swing.JComboBox<>();
                jLabel15 = new javax.swing.JLabel();
                tarif = new javax.swing.JTextField();
                jLabel17 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jLabel20 = new javax.swing.JLabel();
                totalBayar = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();
                hargaTarif = new javax.swing.JTextField();
                jLabel16 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                uangBayar = new javax.swing.JTextField();
                jLabel22 = new javax.swing.JLabel();
                uangKembali = new javax.swing.JTextField();
                jLabel18 = new javax.swing.JLabel();
                tampilanTotal = new javax.swing.JTextField();

                jLabel4.setText("jLabel4");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(242, 151, 15));

                jPanel2.setBackground(new java.awt.Color(242, 151, 15));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setText("FOOD COURT");

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("Oishi Ne");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(417, 417, 417)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(26, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MINUMAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("PILIH MINUMAN");

                minuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Air Mineral", "Juice" }));
                minuman.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                minumanActionPerformed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("HARGA MINUMAN");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("JUMLAH");

                jumlahMinuman.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlahMinumanActionPerformed(evt);
                        }
                });
                jumlahMinuman.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jumlahMinumanKeyPressed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(hargaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(87, 87, 87))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(minuman, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jumlahMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel8))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(minuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jumlahMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(hargaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))))
                                .addContainerGap(116, Short.MAX_VALUE))
                );

                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAKET MAKANAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel9.setText("PILIH PAKET MAKANAN");

                paketMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "PAKET 1", "PAKET 2", "PAKET 3" }));
                paketMakanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                paketMakananActionPerformed(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel11.setText("HARGA PAKET");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel12.setText("JUMLAH");

                jumlahPaketMakanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlahPaketMakananActionPerformed(evt);
                        }
                });
                jumlahPaketMakanan.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jumlahPaketMakananKeyPressed(evt);
                        }
                });

                jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(209, 209, 209)
                                                                .addComponent(jLabel13))
                                                        .addComponent(hargaPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(107, 107, 107))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(paketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jumlahPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel12)
                                                .addComponent(jumlahPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(paketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(hargaPaketMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(118, Short.MAX_VALUE))
                );

                jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JENIS PELAYANAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel10.setText("PILIH PELAYANAN");

                jenisPelayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Take Away", "Delivery" }));
                jenisPelayanan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jenisPelayananActionPerformed(evt);
                        }
                });

                jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel15.setText("TARIF");

                tarif.setColumns(3);

                jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel10))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jenisPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(107, 107, 107))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jenisPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addContainerGap(118, Short.MAX_VALUE))
                );

                jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL BAYAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

                totalBayar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                totalBayarActionPerformed(evt);
                        }
                });

                jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel14.setText("TOTAL HARGA PAKET & MINUMAN");

                hargaTarif.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hargaTarifActionPerformed(evt);
                        }
                });

                jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel16.setText("HARGA TARIF");

                jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel21.setText("UANG BAYAR");

                uangBayar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                uangBayarActionPerformed(evt);
                        }
                });
                uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                uangBayarKeyPressed(evt);
                        }
                });

                jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel22.setText("UANG KEMBALI");

                uangKembali.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                uangKembaliActionPerformed(evt);
                        }
                });

                jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel18.setText("TOTAL");

                tampilanTotal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tampilanTotalActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel18)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(hargaTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tampilanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(uangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(442, 442, 442)
                                                .addComponent(jLabel20))
                                        .addComponent(jLabel22))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel20))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(hargaTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16))
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tampilanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel18))))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(uangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(63, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel6});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5, jPanel6});

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jumlahMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahMinumanActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlahMinumanActionPerformed

        private void jumlahPaketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPaketMakananActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlahPaketMakananActionPerformed

        private void totalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_totalBayarActionPerformed

        private void paketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketMakananActionPerformed
                // TODO add your handling code here:
		if(paketMakanan.getSelectedItem().toString().equalsIgnoreCase("PILIH")){

			menuHarga.setHargaMinuman(minuman.getSelectedItem().toString());
			hargaMinuman.setText(String.valueOf(menuHarga.getHargaMinuman()));

		}
		else{
			menuHarga.setHargaPaket(paketMakanan.getSelectedItem().toString());
			hargaPaketMakanan.setText(String.valueOf(menuHarga.getHargaPaket()));
		}
        }//GEN-LAST:event_paketMakananActionPerformed

        private void minumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minumanActionPerformed
                // TODO add your handling code here:
		if(minuman.getSelectedItem().toString().equalsIgnoreCase("PILIH")){

			menuHarga.setHargaMinuman(minuman.getSelectedItem().toString());
			hargaMinuman.setText(String.valueOf(menuHarga.getHargaMinuman()));
		}
		else{
			menuHarga.setHargaMinuman(minuman.getSelectedItem().toString());
			hargaMinuman.setText(String.valueOf(menuHarga.getHargaMinuman()));
		}
        }//GEN-LAST:event_minumanActionPerformed

        private void jumlahPaketMakananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahPaketMakananKeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			if(jumlahPaketMakanan.getText().equalsIgnoreCase("")){
				menuHarga.setJumlahPaketMakanan(0);
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

			}
			else {
				menuHarga.setJumlahPaketMakanan(Integer.parseInt(jumlahPaketMakanan.getText()));
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));
			}
		}
        }//GEN-LAST:event_jumlahPaketMakananKeyPressed

        private void jumlahMinumanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahMinumanKeyPressed
                // TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			if(jumlahMinuman.getText().equalsIgnoreCase("")){
				menuHarga.setJumlahMinuman(0);
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));

			}
			else {
				menuHarga.setJumlahMinuman(Integer.parseInt(jumlahMinuman.getText()));
				menuHarga.setTotalBayar();
				totalBayar.setText(String.valueOf(menuHarga.getTotalBayar()));
			}
		}
        }//GEN-LAST:event_jumlahMinumanKeyPressed

        private void jenisPelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisPelayananActionPerformed
                // TODO add your handling code here:
		if(jenisPelayanan.getSelectedItem().toString().equalsIgnoreCase("PILIH")){


		}
		else{
			menuHarga.setPelayanan(jenisPelayanan.getSelectedItem().toString());
			tarif.setText(menuHarga.getPelayanan());
			menuHarga.setHargaTarif();
			hargaTarif.setText(String.valueOf(menuHarga.getHargaTarif()));

			menuHarga.setTotal();
			tampilanTotal.setText(String.valueOf(menuHarga.getTotal()));
			
		}

        }//GEN-LAST:event_jenisPelayananActionPerformed

        private void hargaTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTarifActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaTarifActionPerformed

        private void uangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangBayarActionPerformed
                // TODO add your handling code here:
		
        }//GEN-LAST:event_uangBayarActionPerformed

        private void uangKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangKembaliActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_uangKembaliActionPerformed

        private void tampilanTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilanTotalActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_tampilanTotalActionPerformed

        private void uangBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyPressed
                // TODO add your handling code here:

		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			menuHarga.setUangBayar(Double.parseDouble(uangBayar.getText()));

			menuHarga.setUangKembali();
			uangKembali.setText(String.valueOf(menuHarga.getUangKembali()));

		}
        }//GEN-LAST:event_uangBayarKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormOshiNe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormOshiNe().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField hargaMinuman;
        private javax.swing.JTextField hargaPaketMakanan;
        private javax.swing.JTextField hargaTarif;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JComboBox<String> jenisPelayanan;
        private javax.swing.JTextField jumlahMinuman;
        private javax.swing.JTextField jumlahPaketMakanan;
        private javax.swing.JComboBox<String> minuman;
        private javax.swing.JComboBox<String> paketMakanan;
        private javax.swing.JTextField tampilanTotal;
        private javax.swing.JTextField tarif;
        private javax.swing.JTextField totalBayar;
        private javax.swing.JTextField uangBayar;
        private javax.swing.JTextField uangKembali;
        // End of variables declaration//GEN-END:variables
}
