
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rifky
 */
public class Form_utama extends javax.swing.JFrame {
	private static String username;
	private static String nama;




	/**
	 * Creates new form form_utama
	 */
	public Form_utama() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);


		userLabel.setText(nama);


	}

	public static String getUsername() {
		return username;

	}

	public static void  setUsername(String user) {
		Form_utama.username = user;
	}

	public static String getNama() {
		return nama;
	}

	public static void setNama(String nama) {
		Form_utama.nama = nama;
	}


	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                userLabel = new javax.swing.JLabel();
                kembalikanBuku = new javax.swing.JButton();
                minjamBuku = new javax.swing.JButton();
                jMenuBar1 = new javax.swing.JMenuBar();
                Logout = new javax.swing.JMenu();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(152, 180, 212));
                jPanel1.setLayout(new java.awt.GridBagLayout());

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("SELAMAT DATANG");
                jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

                userLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                userLabel.setText("nama");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                jPanel1.add(userLabel, gridBagConstraints);

                kembalikanBuku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                kembalikanBuku.setText("KEMBALIKAN BUKU");
                kembalikanBuku.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                kembalikanBukuActionPerformed(evt);
                        }
                });

                minjamBuku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                minjamBuku.setText("MINJAM BUKU");
                minjamBuku.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                minjamBukuActionPerformed(evt);
                        }
                });

                Logout.setText("Logout");
                Logout.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                LogoutMouseClicked(evt);
                        }
                });
                jMenuBar1.add(Logout);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(579, 579, 579)
                                .addComponent(minjamBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(kembalikanBuku)
                                .addContainerGap(494, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(minjamBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kembalikanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(157, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void minjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minjamBukuActionPerformed
                // TODO add your handling code here:
		new Form_pencarian_buku().show();
		this.dispose();
		
        }//GEN-LAST:event_minjamBukuActionPerformed

        private void kembalikanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanBukuActionPerformed
                // TODO add your handling code here:
		new Form_kembalikan_buku().show();
		this.dispose();
        }//GEN-LAST:event_kembalikanBukuActionPerformed

        private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
                // TODO add your handling code here:
		new Form_login().show();
		this.dispose();
        }//GEN-LAST:event_LogoutMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Form_utama().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu Logout;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JButton kembalikanBuku;
        private javax.swing.JButton minjamBuku;
        private javax.swing.JLabel userLabel;
        // End of variables declaration//GEN-END:variables
}
