/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.trouble.java;

/**
 *
 * @author rifky
 */
public class FormRumah extends javax.swing.JFrame {
	Rumah rmh = new Rumah();

    /** Creates new form FormRumah */
    public FormRumah() {
        initComponents();
	nonaktif();
	bhitung.setEnabled(false);
    }

    private void aktif() {
	cmblok.setEnabled(true);
    }

    private void bersih(){
	cmblok.setSelectedItem("PILIH");
	cbjog.setSelected(false);
	cbsw.setSelected(false);
	cbgy.setSelected(false);
	Bg.clearSelection();
	thrg.setText("");
	tbtn.setText("");
	tother.setText("");
	ttot.setText("");

	rmh.hrg = 0;
	rmh.hrg_j = 0;
	rmh.hrg_g = 0;
	rmh.hrg_s = 0;
	rmh.total = 0;
	rmh.biaya = 0;

	bhitung.setEnabled(false);

    }

     private void nonaktif(){
	cmblok.setEnabled(false);
	cbjog.setEnabled(false);
	cbgy.setEnabled(false);
	cbsw.setEnabled(false);
	rbbtn.setEnabled(false);
	rbob.setEnabled(false);
	thrg.setEnabled(false);
	tbtn.setEnabled(false);
	tother.setEnabled(false);
	ttot.setEnabled(false);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Bg = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                Data_Rumah = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                cmblok = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                thrg = new javax.swing.JTextField();
                Fasilitas_Rumah = new javax.swing.JPanel();
                cbjog = new javax.swing.JCheckBox();
                cbsw = new javax.swing.JCheckBox();
                cbgy = new javax.swing.JCheckBox();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                Pembayaran = new javax.swing.JPanel();
                rbbtn = new javax.swing.JRadioButton();
                rbob = new javax.swing.JRadioButton();
                tbtn = new javax.swing.JTextField();
                tother = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                ttot = new javax.swing.JTextField();
                bhitung = new javax.swing.JButton();
                bbersih = new javax.swing.JButton();
                bkeluar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(153, 153, 153));

                jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 51));
                jLabel1.setText("DEVELOPER PERUMAHAN");
                jLabel1.setToolTipText("");
                jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

                jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 51));
                jLabel2.setText("PT.RUMAH MURAH MERIAH");

                Data_Rumah.setBackground(new java.awt.Color(238, 238, 238));
                Data_Rumah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA RUMAH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel4.setText("Lokasi");

                cmblok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Blok A", "Blok B", "Blok C" }));
                cmblok.setToolTipText("");
                cmblok.setName(""); // NOI18N
                cmblok.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmblokActionPerformed(evt);
                        }
                });

                jLabel5.setText("Harga Dasar");

                thrg.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                thrgActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout Data_RumahLayout = new javax.swing.GroupLayout(Data_Rumah);
                Data_Rumah.setLayout(Data_RumahLayout);
                Data_RumahLayout.setHorizontalGroup(
                        Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Data_RumahLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(46, 46, 46)
                                .addGroup(Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmblok, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                );
                Data_RumahLayout.setVerticalGroup(
                        Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Data_RumahLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(cmblok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Data_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE))
                );

                Fasilitas_Rumah.setBackground(new java.awt.Color(238, 238, 238));
                Fasilitas_Rumah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FASILITAS RUMAH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                cbjog.setText("Jogging Track");
                cbjog.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbjogActionPerformed(evt);
                        }
                });

                cbsw.setText("Swimming Pool");
                cbsw.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbswActionPerformed(evt);
                        }
                });

                cbgy.setText("Gymnasium");
                cbgy.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbgyActionPerformed(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("Rp.100.000,00");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel8.setText("Rp.200.000,00");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel9.setText("Rp.300.000,00");

                javax.swing.GroupLayout Fasilitas_RumahLayout = new javax.swing.GroupLayout(Fasilitas_Rumah);
                Fasilitas_Rumah.setLayout(Fasilitas_RumahLayout);
                Fasilitas_RumahLayout.setHorizontalGroup(
                        Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Fasilitas_RumahLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Fasilitas_RumahLayout.createSequentialGroup()
                                                .addComponent(cbjog, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Fasilitas_RumahLayout.createSequentialGroup()
                                                .addComponent(cbsw, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Fasilitas_RumahLayout.createSequentialGroup()
                                                .addComponent(cbgy, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                Fasilitas_RumahLayout.setVerticalGroup(
                        Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Fasilitas_RumahLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbjog)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbsw)
                                        .addComponent(jLabel8))
                                .addGap(12, 12, 12)
                                .addGroup(Fasilitas_RumahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbgy)
                                        .addComponent(jLabel9))
                                .addContainerGap(26, Short.MAX_VALUE))
                );

                Pembayaran.setBackground(new java.awt.Color(238, 238, 238));
                Pembayaran.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CARA PEMBAYARAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                Bg.add(rbbtn);
                rbbtn.setText("BTN");
                rbbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbbtnActionPerformed(evt);
                        }
                });

                Bg.add(rbob);
                rbob.setText("Other Bank");
                rbob.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbobActionPerformed(evt);
                        }
                });

                tbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tbtnActionPerformed(evt);
                        }
                });

                tother.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                totherActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout PembayaranLayout = new javax.swing.GroupLayout(Pembayaran);
                Pembayaran.setLayout(PembayaranLayout);
                PembayaranLayout.setHorizontalGroup(
                        PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PembayaranLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(PembayaranLayout.createSequentialGroup()
                                                .addComponent(rbbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PembayaranLayout.createSequentialGroup()
                                                .addComponent(rbob, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tother)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                PembayaranLayout.setVerticalGroup(
                        PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PembayaranLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbob)
                                        .addComponent(tother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel11.setText("Total");

                ttot.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ttotActionPerformed(evt);
                        }
                });

                bhitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                bhitung.setText("HITUNG");
                bhitung.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bhitungActionPerformed(evt);
                        }
                });

                bbersih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                bbersih.setText("BERSIH");
                bbersih.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bbersihActionPerformed(evt);
                        }
                });

                bkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                bkeluar.setText("KELUAR");
                bkeluar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bkeluarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Data_Rumah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Fasilitas_Rumah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(bhitung)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(bbersih)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(bkeluar))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(12, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data_Rumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fasilitas_Rumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bhitung)
                                        .addComponent(bbersih)
                                        .addComponent(bkeluar))
                                .addContainerGap(39, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void thrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thrgActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_thrgActionPerformed

        private void cbjogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjogActionPerformed
                // TODO add your handling code here:
		String j;
		if(cbjog.isSelected()){
			j=cbjog.getText();
			rmh.setJog(j);
			rmh.getJog();
		}
		else{
			j="";
			rmh.setJog(j);
			rmh.getJog();
		}
        }//GEN-LAST:event_cbjogActionPerformed

        private void cbswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbswActionPerformed
                // TODO add your handling code here:
		String s;
		if(cbsw.isSelected()){
			s=cbsw.getText();
			rmh.setSwim(s);
			rmh.getSwim();
		}
		else{
			s="";
			rmh.setSwim(s);
			rmh.getSwim();
		}
        }//GEN-LAST:event_cbswActionPerformed

        private void cbgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgyActionPerformed
                // TODO add your handling code here:
		String g;
		if(cbgy.isSelected()){
			g=cbgy.getText();
			rmh.setGym(g);
			rmh.getGym();
		}
		else{
			g="";
			rmh.setGym(g);
			rmh.getGym();
		}
        }//GEN-LAST:event_cbgyActionPerformed

        private void rbbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbtnActionPerformed
                // TODO add your handling code here:
		rmh.setCara(rbbtn.getText());
		rmh.setSeleksiCara();
		tbtn.setText(rmh.getBiaya());
		tother.setText("");
		bhitung.setEnabled(true);
        }//GEN-LAST:event_rbbtnActionPerformed

        private void rbobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbobActionPerformed
                // TODO add your handling code here:
		rmh.setCara(rbob.getText());
		rmh.setSeleksiCara();
		tother.setText(rmh.getBiaya());
		tbtn.setText("");
		bhitung.setEnabled(true);
        }//GEN-LAST:event_rbobActionPerformed

        private void tbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_tbtnActionPerformed

        private void totherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totherActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_totherActionPerformed

        private void ttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_ttotActionPerformed

	
        private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
                // TODO add your handling code here:
		System.exit(0);
        }//GEN-LAST:event_bkeluarActionPerformed

        private void cmblokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblokActionPerformed
                // TODO add your handling code here:
		if (cmblok.getSelectedItem().toString().equalsIgnoreCase("PILIH")){
			rmh.setLokasi(cmblok.getSelectedItem().toString());
			rmh.setSeleksiLok();
			thrg.setText("");// diganti jadi integer

			cbjog.setEnabled(false);
			cbsw.setEnabled(false);
			cbgy.setEnabled(false);

			rbbtn.setEnabled(false);
			rbob.setEnabled(false);
		}
		else {
			rmh.setLokasi(cmblok.getSelectedItem().toString());
			rmh.setSeleksiLok();
			thrg.setText(rmh.setHrg()); // diganti jadi integer

			cbjog.setEnabled(true);
			cbsw.setEnabled(true);
			cbgy.setEnabled(true);

			rbbtn.setEnabled(true);
			rbob.setEnabled(true);
		}
        }//GEN-LAST:event_cmblokActionPerformed

        private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
                // TODO add your handling code here:
		thrg.setText(rmh.setHrg());
		ttot.setText(rmh.getTotal());

        }//GEN-LAST:event_bhitungActionPerformed

        private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
                // TODO add your handling code here:
		bersih();
		aktif();
        }//GEN-LAST:event_bbersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRumah().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup Bg;
        private javax.swing.JPanel Data_Rumah;
        private javax.swing.JPanel Fasilitas_Rumah;
        private javax.swing.JPanel Pembayaran;
        private javax.swing.JButton bbersih;
        private javax.swing.JButton bhitung;
        private javax.swing.JButton bkeluar;
        private javax.swing.JCheckBox cbgy;
        private javax.swing.JCheckBox cbjog;
        private javax.swing.JCheckBox cbsw;
        private javax.swing.JComboBox<String> cmblok;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JRadioButton rbbtn;
        private javax.swing.JRadioButton rbob;
        private javax.swing.JTextField tbtn;
        private javax.swing.JTextField thrg;
        private javax.swing.JTextField tother;
        private javax.swing.JTextField ttot;
        // End of variables declaration//GEN-END:variables

}
