/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.penjualanmotor.java;


/**
 *
 * @author rifky
 */
public class FormMotor extends javax.swing.JFrame {
	Motor motor = new Motor();

	/**
	 * Creates new form formMotor
	 */
	public FormMotor() {
		initComponents();
		nonaktif();


	}

	void namaPembeli_off(){
		namaPembeli_textField.setText("");
	}
	void merkMotor_off(){
		motor.setMerkMotor("");
		merekMotor_comboBox.setSelectedIndex(0);
	}

	void jenisMotor_on() {
		bebek_radioButton.setEnabled(true);
		matic_radioButton.setEnabled(true);
		sport_radioButton.setEnabled(true);
	}

	void jenisMotor_off() {


		jenisMotor_buttonGroup.clearSelection();

		bebek_radioButton.setEnabled(false);
		matic_radioButton.setEnabled(false);
		sport_radioButton.setEnabled(false);

		motor.setMerkMotor("");
		motor.setJenisMotor("");
	}

	void hargaMotor_off(){
		motor.setHargaMotor();
		hargaMotor_textField.setText("");
		hargaMotor_textField.setEnabled(false);
	}

	void jenisBayar_off(){
		jenisBayar_comboBox.setSelectedIndex(0);
		jenisBayar_comboBox.setEnabled(false);
	}

	void jenisBayar_on(){
		jenisBayar_comboBox.setEnabled(true);
	}

	void diskon_off(){
		motor.setDiskon();
		hitungDiskon_button.setEnabled(false);
		diskon_textField.setText("");
		diskon_textField.setEnabled(false);
	}

	void totalBayar_off(){
		motor.setTotalBayar();
		totalBayar_textField.setText("");
		totalBayar_textField.setEnabled(false);

	}

	private void hitungTotal_off(){
		hitungTotal.setEnabled(false);
	}

	void hitungTotal_on(){
		hitungTotal.setEnabled(true);

	}

	void baru_off(){
		baru.setEnabled(false);
	}

	void baru_on(){
		baru.setEnabled(true);
	}
	

	void bersih(){
		namaPembeli_off();
		merkMotor_off();
		jenisMotor_off();
		hargaMotor_off();
		jenisBayar_off();
		diskon_off();
		totalBayar_off();
		baru_off();
		hitungTotal_off();

	}

	private void nonaktif(){
		bebek_radioButton.setEnabled(false);
		matic_radioButton.setEnabled(false);
		sport_radioButton.setEnabled(false);
		hargaMotor_textField.setEnabled(false);
		jenisBayar_comboBox.setEnabled(false);
		hitungDiskon_button.setEnabled(false);
		diskon_textField.setEnabled(false);
		totalBayar_textField.setEnabled(false);
		baru.setEnabled(false);
		hitungTotal.setEnabled(false);
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jenisMotor_buttonGroup = new javax.swing.ButtonGroup();
                jPanel4 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                diskon_textField = new javax.swing.JTextField();
                totalBayar_textField = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                merekMotor_comboBox = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                bebek_radioButton = new javax.swing.JRadioButton();
                sport_radioButton = new javax.swing.JRadioButton();
                matic_radioButton = new javax.swing.JRadioButton();
                hargaMotor_textField = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                namaPembeli_textField = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jenisBayar_comboBox = new javax.swing.JComboBox<>();
                hitungDiskon_button = new javax.swing.JButton();
                baru = new javax.swing.JButton();
                hitungTotal = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("APLIKASI PENJUALAN MOTOR");

                jPanel1.setBackground(new java.awt.Color(102, 102, 255));

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel8.setText("DEALER MAJU MOTOR");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel9.setText("FORM PENJUALAN MOTOR");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                .addGap(111, 111, 111))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(31, 31, 31))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA HARGA MOTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
                jPanel2.setToolTipText("");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("DISKON");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("TOTAL BAYAR");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(totalBayar_textField))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(54, 54, 54)
                                                .addComponent(diskon_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(diskon_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(totalBayar_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 7, Short.MAX_VALUE))
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA MOTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
                jPanel3.setToolTipText("");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel2.setText("MERK MOTOR");

                merekMotor_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Honda", "Yamaha" }));
                merekMotor_comboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                merekMotor_comboBoxActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("JENIS MOTOR");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel4.setText("HARGA MOTOR");

                jenisMotor_buttonGroup.add(bebek_radioButton);
                bebek_radioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                bebek_radioButton.setText("BEBEK");
                bebek_radioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bebek_radioButtonActionPerformed(evt);
                        }
                });

                jenisMotor_buttonGroup.add(sport_radioButton);
                sport_radioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                sport_radioButton.setText("SPORT");
                sport_radioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sport_radioButtonActionPerformed(evt);
                        }
                });

                jenisMotor_buttonGroup.add(matic_radioButton);
                matic_radioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                matic_radioButton.setText("MATIC");
                matic_radioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                matic_radioButtonActionPerformed(evt);
                        }
                });

                hargaMotor_textField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hargaMotor_textFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(hargaMotor_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(merekMotor_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(bebek_radioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(matic_radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sport_radioButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(merekMotor_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(bebek_radioButton)
                                        .addComponent(sport_radioButton)
                                        .addComponent(matic_radioButton))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(hargaMotor_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel1.setText("NAMA PEMBELI");

                namaPembeli_textField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                namaPembeli_textFieldActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("JENIS BAYAR");

                jenisBayar_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Cash", "Credit" }));
                jenisBayar_comboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jenisBayar_comboBoxActionPerformed(evt);
                        }
                });

                hitungDiskon_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                hitungDiskon_button.setText("HITUNG DISKON");
                hitungDiskon_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hitungDiskon_buttonActionPerformed(evt);
                        }
                });

                baru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                baru.setText("BARU");
                baru.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                baruActionPerformed(evt);
                        }
                });

                hitungTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                hitungTotal.setText("HITUNG TOTAL");
                hitungTotal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hitungTotalActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton3.setText("SELESAI");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(namaPembeli_textField)))
                                .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jenisBayar_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hitungDiskon_button)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(baru)
                                .addGap(18, 18, 18)
                                .addComponent(hitungTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(84, 84, 84))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(namaPembeli_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jenisBayar_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hitungDiskon_button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(hitungTotal)
                                        .addComponent(jButton3)
                                        .addComponent(baru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(110, Short.MAX_VALUE))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {baru, hitungTotal, jButton3});

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void namaPembeli_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPembeli_textFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_namaPembeli_textFieldActionPerformed

        private void bebek_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebek_radioButtonActionPerformed
                // TODO add your handling code here:
		motor.setJenisMotor(bebek_radioButton.getText());
		motor.setHargaMotor();
		hargaMotor_textField.setText(motor.getHargaMotor().toString());

		jenisBayar_on();

		

        }//GEN-LAST:event_bebek_radioButtonActionPerformed

        private void matic_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matic_radioButtonActionPerformed
                // TODO add your handling code here:
		motor.setJenisMotor(matic_radioButton.getText());
		motor.setHargaMotor();
		hargaMotor_textField.setText(motor.getHargaMotor().toString());
		jenisBayar_on();
        }//GEN-LAST:event_matic_radioButtonActionPerformed

        private void sport_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sport_radioButtonActionPerformed
                // TODO add your handling code here:
		motor.setJenisMotor(sport_radioButton.getText());
		motor.setHargaMotor();
		hargaMotor_textField.setText(motor.getHargaMotor().toString());
		jenisBayar_on();
        }//GEN-LAST:event_sport_radioButtonActionPerformed

        private void hargaMotor_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMotor_textFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_hargaMotor_textFieldActionPerformed

        private void jenisBayar_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBayar_comboBoxActionPerformed
                // TODO add your handling code here:
		if(jenisBayar_comboBox.getSelectedItem().toString().equalsIgnoreCase("pilih")){

			hitungDiskon_button.setEnabled(false);
		}
		else{
			hitungDiskon_button.setEnabled(true);

		}
        }//GEN-LAST:event_jenisBayar_comboBoxActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton3ActionPerformed

        private void merekMotor_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekMotor_comboBoxActionPerformed
                // TODO add your handling code here:
		if(merekMotor_comboBox.getSelectedItem().toString().equalsIgnoreCase("pilih")){
			jenisMotor_off();
			hargaMotor_off();
			jenisBayar_off();
			diskon_off();
			totalBayar_off();

		}
		else{

			motor.setMerkMotor(merekMotor_comboBox.getSelectedItem().toString());
			jenisMotor_on();
			hargaMotor_textField.setEnabled(true);
		}
			
        }//GEN-LAST:event_merekMotor_comboBoxActionPerformed

        private void hitungDiskon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungDiskon_buttonActionPerformed
                // TODO add your handling code here:
		
		motor.setDiskon();
		diskon_textField.setEnabled(true);
		diskon_textField.setText(String.valueOf(motor.getDiskon()));

		hitungTotal_on();
        }//GEN-LAST:event_hitungDiskon_buttonActionPerformed

        private void hitungTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungTotalActionPerformed
                // TODO add your handling code here:
		motor.setTotalBayar();
		totalBayar_textField.setEnabled(true);
		totalBayar_textField.setText(String.valueOf(motor.getTotalBayar()));
		baru_on();
        }//GEN-LAST:event_hitungTotalActionPerformed

        private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
                // TODO add your handling code here:
		bersih();
        }//GEN-LAST:event_baruActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormMotor().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton baru;
        private javax.swing.JRadioButton bebek_radioButton;
        private javax.swing.JTextField diskon_textField;
        private javax.swing.JTextField hargaMotor_textField;
        private javax.swing.JButton hitungDiskon_button;
        private javax.swing.JButton hitungTotal;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JComboBox<String> jenisBayar_comboBox;
        private javax.swing.ButtonGroup jenisMotor_buttonGroup;
        private javax.swing.JRadioButton matic_radioButton;
        private javax.swing.JComboBox<String> merekMotor_comboBox;
        private javax.swing.JTextField namaPembeli_textField;
        private javax.swing.JRadioButton sport_radioButton;
        private javax.swing.JTextField totalBayar_textField;
        // End of variables declaration//GEN-END:variables
}
